= Custom Bree

The projects illustrate an issue I have with tycho and a bundle using `Custom-1.0` value as `Bundle-RequiredExecutionEnvironment`.

----
org.eclipse.tycho.core.ee.UnknownEnvironmentException: Unknown OSGi execution environment: 'Custom-1.0'
----

== P2 Update site

The bundle containing two values (`JavaSE-1.8` and `Custom-1.0`) for the `Bundle-RequiredExecutionEnvironment` header is `some.bundle` located in the `fixture/` folder:

----
Bundle-RequiredExecutionEnvironment: JavaSE-1.8,Custom-1.0
----

In the same folder there is a feature project (`some.feature`) and an update-site project (`some.site`).

The resulting P2 repository was built using Eclipse IDE (with PDE tooling) and is published on GitHub.
It is accessible at this location:

----
https://raw.githubusercontent.com/jmini/tycho-experiments/master/customBree/fixture/some.site
----

== Tycho

The tycho project consist of 2 maven modules:

* `fr.jmini.tycho.custom.targetplatform` to define the target platform (using the Update Site created before)
* `fr.jmini.tycho.custom.product` to define a product that should be materialized (Create the zip containing the application)

When you are in the `customBree` project, just run

----
mvn verify
----

== Complete stacktrace

----
[ERROR] Internal error: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST ~/.m2/repository/p2/osgi/bundle/some.bundle/1.0.0.202103301352/some.bundle-1.0.0.202103301352.jar!/META-INF/MANIFEST.MF: Unknown OSGi execution environment: 'Custom-1.0' -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST ~/.m2/repository/p2/osgi/bundle/some.bundle/1.0.0.202103301352/some.bundle-1.0.0.202103301352.jar!/META-INF/MANIFEST.MF: Unknown OSGi execution environment: 'Custom-1.0'
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:120)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST ~/.m2/repository/p2/osgi/bundle/some.bundle/1.0.0.202103301352/some.bundle-1.0.0.202103301352.jar!/META-INF/MANIFEST.MF: Unknown OSGi execution environment: 'Custom-1.0'
    at org.eclipse.tycho.core.osgitools.OsgiManifest.parseExecutionEnvironments (OsgiManifest.java:69)
    at org.eclipse.tycho.core.osgitools.OsgiManifest.<init> (OsgiManifest.java:55)
    at org.eclipse.tycho.core.osgitools.OsgiManifest.parse (OsgiManifest.java:152)
    at org.eclipse.tycho.core.osgitools.DefaultBundleReader.loadManifestFromFile (DefaultBundleReader.java:83)
    at org.eclipse.tycho.core.osgitools.DefaultBundleReader.doLoadManifest (DefaultBundleReader.java:62)
    at org.eclipse.tycho.core.osgitools.DefaultBundleReader.loadManifest (DefaultBundleReader.java:51)
    at org.eclipse.tycho.core.maven.MavenDependencyInjector.getClasspathElements (MavenDependencyInjector.java:118)
    at org.eclipse.tycho.core.maven.MavenDependencyInjector.newExternalDependencies (MavenDependencyInjector.java:89)
    at org.eclipse.tycho.core.maven.MavenDependencyInjector.addDependency (MavenDependencyInjector.java:72)
    at org.eclipse.tycho.core.maven.MavenDependencyInjector.injectMavenDependencies (MavenDependencyInjector.java:50)
    at org.eclipse.tycho.p2.resolver.P2DependencyResolver.injectDependenciesIntoMavenModel (P2DependencyResolver.java:436)
    at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject (DefaultTychoResolver.java:153)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead (TychoMavenLifecycleParticipant.java:95)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:264)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.eclipse.tycho.core.ee.UnknownEnvironmentException: Unknown OSGi execution environment: 'Custom-1.0'
    at org.eclipse.tycho.core.ee.ExecutionEnvironmentUtils.getExecutionEnvironment (ExecutionEnvironmentUtils.java:85)
    at org.eclipse.tycho.core.osgitools.OsgiManifest.parseExecutionEnvironments (OsgiManifest.java:66)
    at org.eclipse.tycho.core.osgitools.OsgiManifest.<init> (OsgiManifest.java:55)
    at org.eclipse.tycho.core.osgitools.OsgiManifest.parse (OsgiManifest.java:152)
    at org.eclipse.tycho.core.osgitools.DefaultBundleReader.loadManifestFromFile (DefaultBundleReader.java:83)
    at org.eclipse.tycho.core.osgitools.DefaultBundleReader.doLoadManifest (DefaultBundleReader.java:62)
    at org.eclipse.tycho.core.osgitools.DefaultBundleReader.loadManifest (DefaultBundleReader.java:51)
    at org.eclipse.tycho.core.maven.MavenDependencyInjector.getClasspathElements (MavenDependencyInjector.java:118)
    at org.eclipse.tycho.core.maven.MavenDependencyInjector.newExternalDependencies (MavenDependencyInjector.java:89)
    at org.eclipse.tycho.core.maven.MavenDependencyInjector.addDependency (MavenDependencyInjector.java:72)
    at org.eclipse.tycho.core.maven.MavenDependencyInjector.injectMavenDependencies (MavenDependencyInjector.java:50)
    at org.eclipse.tycho.p2.resolver.P2DependencyResolver.injectDependenciesIntoMavenModel (P2DependencyResolver.java:436)
    at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject (DefaultTychoResolver.java:153)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead (TychoMavenLifecycleParticipant.java:95)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:264)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
----

== Tycho version

As you can see the problem is present with Tycho version `1.7.0` but fixed with version `2.2.0`

The tycho version is defined as property in the `pom.xml` of the `customBree` folder:

[source, xml]
----
<properties>
    <tycho-version>1.7.0</tycho-version>
</properties>
----